### PR TITLE
Proper graphics

### PR DESCRIPTION
**Pull request by jonjohansen**
Created proper vector graphics of the logo in PDF and SVG format.
Rendered two pretty large PNG files from the logo, so we have them at our disposal where vector graphics is not supported.
The optimal would be to scale them down to appropriate size, as the files themselves are rather large.

Note: If other graphic formats/sizes are required feel free to shoot me a message.

🖊 🥇 🔵 🔴 🔶 💫

### CODE REVIEW

**Comment by MaxJohansen** [comment]
Why am I not allowed to review this?

**Review by MaxJohansen — APPROVED** [review]

**Comment by IsakSundeSingh** [comment]
Cuz ya noob

**Review by vebjornhaugland — APPROVED** [review]
Love the dumps 💯

**Review by IsakSundeSingh — APPROVED** [review]
So good 👍 ✨

**Pull request merged**
